import { createApplication } from "@specific-dev/framework";
import * as schema from './src/db/schema/schema.js';

const app = await createApplication(schema);

const peptideData = [
  // GLP-1 Agonists (10+)
  {
    name: 'Semaglutide',
    description: 'GLP-1 receptor agonist for weight management and blood sugar control with long-acting effects',
    category: 'GLP-1',
    benefits: 'Weight loss, Blood sugar control, Appetite suppression, Cardiovascular protection, Sustained satiety',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Injection site reactions',
    dosage_min: '0.25 mg',
    dosage_max: '2.4 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Tirzepatide',
    description: 'Dual GIP/GLP-1 receptor agonist for diabetes and weight loss with synergistic effects',
    category: 'GLP-1',
    benefits: 'Superior weight loss, Blood sugar control, Dual mechanism, Increased insulin sensitivity, Sustained benefit',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Injection site irritation',
    dosage_min: '2.5 mg',
    dosage_max: '15 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Liraglutide',
    description: 'GLP-1 analog for type 2 diabetes and obesity with once or twice daily dosing',
    category: 'GLP-1',
    benefits: 'Weight loss, Blood sugar management, Cardiovascular benefits, Appetite reduction, Improved glycemic control',
    side_effects: 'Nausea, Headache, Diarrhea, Vomiting, Constipation',
    dosage_min: '0.6 mg',
    dosage_max: '3.0 mg',
    frequency: 'Once or twice daily',
    timing: 'Morning or morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Dulaglutide',
    description: 'Long-acting GLP-1 receptor agonist with extended half-life for weekly dosing',
    category: 'GLP-1',
    benefits: 'Weekly dosing, Weight reduction, Blood glucose control, Cardiovascular protection, Consistent levels',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosage_min: '0.75 mg',
    dosage_max: '4.5 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Exenatide',
    description: 'GLP-1 mimetic for blood glucose control with short or extended-release formulations',
    category: 'GLP-1',
    benefits: 'Blood sugar control, Weight loss, Multiple daily injection option, Appetite suppression, Proven efficacy',
    side_effects: 'Nausea, Vomiting, Hypoglycemia, Headache, Weakness',
    dosage_min: '5 mcg',
    dosage_max: '10 mcg',
    frequency: 'Twice daily or once weekly',
    timing: 'Before meals (twice daily) or any time (weekly)',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Albiglutide',
    description: 'Weekly GLP-1 receptor agonist with extended duration of action',
    category: 'GLP-1',
    benefits: 'Weekly dosing, Blood sugar control, Weight reduction, Cardiovascular effects, Simplified regimen',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosage_min: '30 mg',
    dosage_max: '50 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Lixisenatide',
    description: 'Short-acting GLP-1 receptor agonist with rapid onset and short duration',
    category: 'GLP-1',
    benefits: 'Rapid onset, Blood sugar control, Weight reduction, Meal-time dosing, Safety profile',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosage_min: '10 mcg',
    dosage_max: '20 mcg',
    frequency: 'Once daily',
    timing: 'Within 1 hour before first meal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Semaglutide (Oral)',
    description: 'First oral GLP-1 receptor agonist with absorption enhancer for convenience',
    category: 'GLP-1',
    benefits: 'Oral administration, Weight loss, Blood sugar control, No injections, Good compliance',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosage_min: '3 mg',
    dosage_max: '14 mg',
    frequency: 'Once daily',
    timing: 'Early morning with water only',
    administration_route: 'Oral',
  },
  {
    name: 'Retatrutide',
    description: 'Triple agonist of GLP-1/GIP/Glucagon receptors for superior metabolic effects',
    category: 'GLP-1',
    benefits: 'Triple mechanism, Superior weight loss, Metabolic improvement, Glucose control, Enhanced lipid profile',
    side_effects: 'Nausea, Vomiting, Diarrhea, Injection site reaction, Headache',
    dosage_min: '1 mg',
    dosage_max: '8 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'CagriSema',
    description: 'Combination peptide of cagrilintide and semaglutide for enhanced weight loss',
    category: 'GLP-1',
    benefits: 'Synergistic effect, Greater weight loss, Blood sugar control, Dual mechanism, Sustained satiety',
    side_effects: 'Nausea, Vomiting, Diarrhea, Constipation, Gastrointestinal effects',
    dosage_min: '0.25 mg',
    dosage_max: '2.4 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },

  // Growth Hormone & Secretagogues (15+)
  {
    name: 'CJC-1295',
    description: 'GHRH analog for stimulating growth hormone release with long-acting properties',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Anti-aging, Improved recovery',
    side_effects: 'Flushing, Headache, Dizziness, Hunger increase, Hyperglycemia',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Once daily or 3x weekly',
    timing: 'Evening or before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Ipamorelin',
    description: 'Selective GH secretagogue with minimal side effects and safety profile',
    category: 'Growth Hormone',
    benefits: 'Natural GH stimulation, Muscle preservation, Minimal cortisol elevation, Good safety, Appetite stimulation',
    side_effects: 'Mild hunger increase, Slight hyperglycemia, Rare flushing, Minimal side effects, Generally well-tolerated',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening and before bed optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHRP-2',
    description: 'Growth hormone releasing peptide with dual signaling mechanism for GH stimulation',
    category: 'Growth Hormone',
    benefits: 'Powerful GH release, Appetite stimulation, Muscle growth support, Improved sleep, Synergistic with GHRH',
    side_effects: 'Appetite increase, Water retention, Hyperglycemia, Prolactin elevation, Potential pituitary downregulation',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHRP-6',
    description: 'GH secretagogue with pronounced appetite stimulation and GH release effects',
    category: 'Growth Hormone',
    benefits: 'Potent GH release, Strong appetite stimulation, Muscle growth, Improved recovery, Enhanced growth signaling',
    side_effects: 'Significant appetite increase, Water retention, Hyperglycemia, Potential tolerance development, Cortisol elevation',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Hexarelin',
    description: 'Potent GH releasing peptide with strong GH secretion properties',
    category: 'Growth Hormone',
    benefits: 'Strong GH stimulation, Muscle building, Cardiovascular tone, Anti-aging effects, Powerful secretagogue',
    side_effects: 'Cortisol elevation, Potential prolactin increase, Hyperglycemia, Tolerance possible, Water retention',
    dosage_min: '100 mcg',
    dosage_max: '200 mcg',
    frequency: 'One to two times daily',
    timing: 'Evening optimal, before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Sermorelin',
    description: 'GHRH analog for stimulating natural GH production with physiological effects',
    category: 'Growth Hormone',
    benefits: 'Natural GH stimulation, Muscle growth, Fat loss, Improved sleep quality, Anti-aging benefits',
    side_effects: 'Mild headache, Flushing, Nausea, Water retention, Mild hyperglycemia',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Once daily',
    timing: 'Evening or before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Tesamorelin',
    description: 'GHRH analog specifically for reducing lipodystrophy and visceral fat',
    category: 'Growth Hormone',
    benefits: 'Visceral fat reduction, Improved body composition, Metabolic improvement, Cardiovascular benefits, GH stimulation',
    side_effects: 'Joint pain, Carpal tunnel syndrome, Hyperglycemia, Water retention, Headache',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'MK-677 (Ibutamoren)',
    description: 'Oral GH secretagogue and ghrelin mimetic with non-peptide structure',
    category: 'Growth Hormone',
    benefits: 'Oral administration, GH stimulation, Appetite increase, Muscle growth, Improved sleep, Convenient dosing',
    side_effects: 'Increased appetite, Water retention, Hyperglycemia, Mild headache, Potential prolactin elevation',
    dosage_min: '10 mg',
    dosage_max: '25 mg',
    frequency: 'Once daily',
    timing: 'Evening for sleep benefits',
    administration_route: 'Oral',
  },
  {
    name: 'CJC-1295 DAC',
    description: 'Long-acting GHRH analog with extended half-life for less frequent dosing',
    category: 'Growth Hormone',
    benefits: 'Extended half-life, Less frequent dosing, Sustained GH release, Muscle growth, Fat loss potential',
    side_effects: 'Flushing, Hyperglycemia, Potential tolerance, Headache, Water retention',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'MOD-GRF 1-29',
    description: 'Modified growth hormone releasing factor without DAC for shorter-acting effects',
    category: 'Growth Hormone',
    benefits: 'Short-acting GHRH, Pulse-like GH release, Multiple daily dosing option, Synergistic with secretagogues',
    side_effects: 'Mild flushing, Headache, Hyperglycemia, Water retention, Generally well-tolerated',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'One to three times daily',
    timing: 'Evening and before bed optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHRP-4',
    description: 'Fourth generation GH releasing peptide with optimized profile',
    category: 'Growth Hormone',
    benefits: 'Balanced GH stimulation, Improved profile vs earlier GHRPs, Muscle support, Fat loss, Well-tolerated',
    side_effects: 'Mild appetite increase, Slight hyperglycemia, Minimal prolactin effect, Water retention, Generally safe',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Anamorelin',
    description: 'Oral ghrelin mimetic for appetite stimulation and muscle preservation',
    category: 'Growth Hormone',
    benefits: 'Oral administration, Appetite stimulation, Muscle preservation, GH signaling, Lean mass support',
    side_effects: 'Increased appetite, Headache, Hyperglycemia, Dizziness, Potential glucose elevation',
    dosage_min: '50 mg',
    dosage_max: '100 mg',
    frequency: 'Once daily',
    timing: 'Morning with food',
    administration_route: 'Oral',
  },
  {
    name: 'Pralmorelin',
    description: 'GHRP-2 derivative with similar growth hormone releasing effects',
    category: 'Growth Hormone',
    benefits: 'Potent GH release, Muscle growth, Appetite stimulation, Recovery support, Improved training response',
    side_effects: 'Appetite increase, Hyperglycemia, Water retention, Possible prolactin effect, Potential tolerance',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Examorelin',
    description: 'Hexarelin analog with optimized GH releasing properties',
    category: 'Growth Hormone',
    benefits: 'Strong GH stimulation, Muscle building, Improved body composition, Cardiovascular support, Potent effect',
    side_effects: 'Cortisol elevation, Water retention, Hyperglycemia, Possible tolerance, Prolactin elevation',
    dosage_min: '100 mcg',
    dosage_max: '200 mcg',
    frequency: 'One to two times daily',
    timing: 'Evening before bed optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Capromorelin',
    description: 'Oral ghrelin agonist with appetite stimulation and growth signaling',
    category: 'Growth Hormone',
    benefits: 'Oral dosing, Appetite stimulation, GH signaling, Muscle preservation, Convenient administration',
    side_effects: 'Increased appetite, Headache, Hyperglycemia, Dizziness, Potential glucose elevation',
    dosage_min: '30 mg',
    dosage_max: '100 mg',
    frequency: 'Once daily',
    timing: 'Before meals or morning',
    administration_route: 'Oral',
  },

  // Recovery & Healing (15+)
  {
    name: 'BPC-157',
    description: 'Body protection compound for rapid tissue repair and healing of injuries',
    category: 'Recovery',
    benefits: 'Tissue repair, Muscle recovery, Joint healing, Anti-inflammatory, Improved healing speed',
    side_effects: 'Generally well-tolerated, Rare mild headache, Minimal systemic effects, Safe profile, Few side effects',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'TB-500 (Thymosin Beta-4)',
    description: 'Powerful healing peptide promoting tissue repair and muscle recovery effects',
    category: 'Recovery',
    benefits: 'Rapid healing, Tissue regeneration, Muscle repair, Anti-inflammatory, Improved recovery time',
    side_effects: 'Headache, Mild nausea, Dizziness, Rare light sensitivity, Generally well-tolerated',
    dosage_min: '2 mg',
    dosage_max: '4 mg',
    frequency: 'Once weekly or twice weekly',
    timing: 'Morning, any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHK-Cu',
    description: 'Copper peptide for wound healing, skin rejuvenation, and tissue repair',
    category: 'Recovery',
    benefits: 'Wound healing, Skin rejuvenation, Collagen production, Anti-aging, Tissue restoration',
    side_effects: 'Minimal side effects, Rare skin irritation, Occasional taste disturbance, Generally safe, Well-tolerated',
    dosage_min: '1 mg',
    dosage_max: '3 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Epithalon',
    description: 'Telomerase activator peptide for longevity and cellular age reversal',
    category: 'Recovery',
    benefits: 'Telomerase activation, Anti-aging, Cellular rejuvenation, Longevity support, Age-related improvement',
    side_effects: 'Minimal side effects, Rare headache, Generally well-tolerated, Safe long-term use, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Evening or morning',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Dihexa',
    description: 'Cognitive enhancer and neurogenesis promoter with brain-derived neurotrophic factor effects',
    category: 'Recovery',
    benefits: 'Neurogenesis promotion, Cognitive enhancement, Neuroprotection, Memory improvement, Brain cell growth',
    side_effects: 'Mild headache, Rare dizziness, Generally well-tolerated, Minimal systemic effects, Safe profile',
    dosage_min: '100 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Intranasal',
  },
  {
    name: 'Cerebrolysin',
    description: 'Neurotrophic peptide mixture supporting brain function and neuroprotection',
    category: 'Recovery',
    benefits: 'Neuroprotection, Brain cell support, Cognitive enhancement, Stroke recovery, Memory improvement',
    side_effects: 'Mild headache, Rare dizziness, Nausea, Injection site irritation, Generally safe',
    dosage_min: '5 mL',
    dosage_max: '10 mL',
    frequency: 'Daily or three times weekly',
    timing: 'Morning optimal',
    administration_route: 'Intramuscular',
  },
  {
    name: 'Semax',
    description: 'Nootropic peptide for cognitive enhancement and neuroprotection without addiction',
    category: 'Recovery',
    benefits: 'Cognitive enhancement, Memory improvement, Neuroprotection, Stress resilience, Brain function support',
    side_effects: 'Minimal side effects, Rare headache, Mild insomnia if dosed late, Generally well-tolerated, Safe',
    dosage_min: '50 mcg',
    dosage_max: '200 mcg',
    frequency: 'Once to three times daily',
    timing: 'Morning and afternoon optimal',
    administration_route: 'Intranasal',
  },
  {
    name: 'Selank',
    description: 'Anxiolytic and nootropic peptide with anti-anxiety and cognitive benefits',
    category: 'Recovery',
    benefits: 'Anxiety reduction, Cognitive enhancement, Anti-stress, Mood improvement, Neuroprotection',
    side_effects: 'Minimal side effects, Rare headache, Occasional mild dizziness, Generally safe, Well-tolerated',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and afternoon',
    administration_route: 'Intranasal',
  },
  {
    name: 'P21',
    description: 'Cognitive enhancer derived from CNTF with neuroprotective effects',
    category: 'Recovery',
    benefits: 'Cognitive enhancement, Neuroprotection, Memory improvement, Brain cell support, Neural preservation',
    side_effects: 'Mild headache, Rare dizziness, Minimal side effects, Generally well-tolerated, Safe profile',
    dosage_min: '100 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning optimal',
    administration_route: 'Intranasal',
  },
  {
    name: 'Thymosin Alpha-1',
    description: 'Immune system modulator supporting thymic function and immune response',
    category: 'Recovery',
    benefits: 'Immune support, Thymic function, Anti-aging, Recovery enhancement, Immune regulation',
    side_effects: 'Minimal side effects, Rare injection site reaction, Generally well-tolerated, Safe, Few adverse events',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Three times weekly',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'LL-37',
    description: 'Antimicrobial peptide with wound healing and immune modulation properties',
    category: 'Recovery',
    benefits: 'Antimicrobial activity, Wound healing, Anti-inflammatory, Improved healing speed, Immune support',
    side_effects: 'Minimal side effects, Rare skin irritation, Minimal systemic effects, Generally safe, Well-tolerated',
    dosage_min: '100 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'As needed for wounds',
    administration_route: 'Topical',
  },
  {
    name: 'KPV',
    description: 'Anti-inflammatory tripeptide with immunomodulatory and gut-protective effects',
    category: 'Recovery',
    benefits: 'Anti-inflammatory, Gut healing, Immune modulation, Reduced inflammation, Intestinal support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare headache, Generally safe, Few adverse events',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Intranasal',
  },
  {
    name: 'ARA-290',
    description: 'Tissue protective peptide with regenerative and neuroprotective properties',
    category: 'Recovery',
    benefits: 'Tissue protection, Neuroprotection, Pain reduction, Tissue repair, Regenerative effects',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '500 mcg',
    dosage_max: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Pentosan Polysulfate',
    description: 'Joint and cartilage support peptide-like compound for cartilage protection',
    category: 'Recovery',
    benefits: 'Joint support, Cartilage protection, Anti-inflammatory, Joint fluid improvement, Pain reduction',
    side_effects: 'Rare gastrointestinal upset, Mild headache, Generally well-tolerated, Few side effects, Safe profile',
    dosage_min: '300 mg',
    dosage_max: '400 mg',
    frequency: 'Three times daily',
    timing: 'With meals',
    administration_route: 'Oral',
  },
  {
    name: 'Larazotide',
    description: 'Tight junction regulator for gut health and intestinal barrier support',
    category: 'Recovery',
    benefits: 'Gut barrier support, Intestinal healing, Leaky gut reduction, Digestive support, Anti-inflammatory',
    side_effects: 'Minimal side effects, Rare abdominal discomfort, Well-tolerated, Generally safe, Few adverse events',
    dosage_min: '0.25 mg',
    dosage_max: '1 mg',
    frequency: 'Three times daily',
    timing: 'Before meals',
    administration_route: 'Oral',
  },

  // Cognitive & Nootropic (10+)
  {
    name: 'Noopept',
    description: 'Cognitive enhancer and neuroprotectant with proven brain-derived neurotrophic factor effects',
    category: 'Cognitive',
    benefits: 'Cognitive enhancement, Memory improvement, Neuroprotection, Focus improvement, Learning enhancement',
    side_effects: 'Minimal side effects, Rare headache, Mild insomnia, Generally well-tolerated, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '30 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and afternoon',
    administration_route: 'Oral',
  },
  {
    name: 'NSI-189',
    description: 'Neurogenesis stimulator supporting brain cell generation for depression management',
    category: 'Cognitive',
    benefits: 'Neurogenesis promotion, Mood improvement, Cognitive enhancement, Depression support, Brain cell growth',
    side_effects: 'Mild headache, Rare dizziness, Generally well-tolerated, Few side effects, Safe profile',
    dosage_min: '40 mg',
    dosage_max: '80 mg',
    frequency: 'Once daily',
    timing: 'Morning optimal',
    administration_route: 'Oral',
  },
  {
    name: 'Cerebrolysin',
    description: 'Neurotrophic factor mixture for cognitive support and neuroprotection',
    category: 'Cognitive',
    benefits: 'Brain cell support, Cognitive enhancement, Neuroprotection, Memory improvement, Brain health',
    side_effects: 'Mild headache, Rare dizziness, Injection site irritation, Generally safe, Well-tolerated',
    dosage_min: '5 mL',
    dosage_max: '10 mL',
    frequency: 'Daily or three times weekly',
    timing: 'Morning optimal',
    administration_route: 'Intramuscular',
  },
  {
    name: 'Cortexin',
    description: 'Neuroprotective peptide complex supporting cognitive function',
    category: 'Cognitive',
    benefits: 'Neuroprotection, Cognitive support, Memory enhancement, Brain function, Anti-stress effects',
    side_effects: 'Minimal side effects, Rare headache, Well-tolerated, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'NA-Semax-Amidate',
    description: 'Enhanced Semax variant with improved absorption and effects',
    category: 'Cognitive',
    benefits: 'Cognitive enhancement, Neuroprotection, Memory support, Enhanced absorption, Longer lasting effects',
    side_effects: 'Minimal side effects, Rare headache, Mild insomnia if late dosed, Generally well-tolerated, Safe',
    dosage_min: '50 mcg',
    dosage_max: '200 mcg',
    frequency: 'Once to three times daily',
    timing: 'Morning and afternoon',
    administration_route: 'Intranasal',
  },
  {
    name: 'NA-Selank',
    description: 'Enhanced Selank variant with improved anxiolytic and cognitive effects',
    category: 'Cognitive',
    benefits: 'Anxiety reduction, Cognitive enhancement, Anti-stress, Mood support, Enhanced absorption',
    side_effects: 'Minimal side effects, Rare headache, Mild dizziness, Generally well-tolerated, Safe',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and afternoon',
    administration_route: 'Intranasal',
  },
  {
    name: 'Adamax',
    description: 'Memory and learning enhancer with neuroprotective properties',
    category: 'Cognitive',
    benefits: 'Memory enhancement, Learning improvement, Cognitive support, Neuroprotection, Brain function',
    side_effects: 'Minimal side effects, Rare headache, Generally well-tolerated, Few adverse events, Safe profile',
    dosage_min: '100 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning optimal',
    administration_route: 'Intranasal',
  },
  {
    name: 'Pinealon',
    description: 'Pineal gland peptide supporting sleep quality and circadian rhythm regulation',
    category: 'Cognitive',
    benefits: 'Sleep support, Circadian rhythm regulation, Melatonin enhancement, Cognitive preservation, Anti-aging',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '3 mg',
    dosage_max: '5 mg',
    frequency: 'Once daily',
    timing: 'Evening before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Vilon',
    description: 'Thymus peptide supporting immune function and cognitive health',
    category: 'Cognitive',
    benefits: 'Immune support, Cognitive preservation, Anti-aging, Thymic function, Overall health support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Epitalon',
    description: 'Pineal peptide for circadian rhythm support and longevity promotion',
    category: 'Cognitive',
    benefits: 'Sleep improvement, Circadian support, Anti-aging, Melatonin regulation, Longevity support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Evening before bed',
    administration_route: 'Subcutaneous',
  },

  // Metabolic & Fat Loss (10+)
  {
    name: 'AOD-9604',
    description: 'Anti-obesity peptide fragment for targeted fat loss without growth effects',
    category: 'Metabolic',
    benefits: 'Fat loss, Metabolism boost, Body composition improvement, No GH effects, Lipolysis promotion',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Few adverse events, Generally safe',
    dosage_min: '300 mcg',
    dosage_max: '600 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Fragment 176-191',
    description: 'HGH fragment specifically designed for fat loss without growth hormone effects',
    category: 'Metabolic',
    benefits: 'Fat loss, Metabolism acceleration, Body composition improvement, Lipolysis, No muscle loss',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Few adverse events, Generally safe',
    dosage_min: '200 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Before cardio or bedtime',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'MOTS-c',
    description: 'Mitochondrial-derived peptide improving metabolism and metabolic health',
    category: 'Metabolic',
    benefits: 'Metabolism improvement, Mitochondrial function, Fat loss, Insulin sensitivity, Metabolic health',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Humanin',
    description: 'Mitochondrial-derived peptide supporting metabolic and cellular health',
    category: 'Metabolic',
    benefits: 'Metabolic support, Cellular health, Anti-aging, Mitochondrial function, Fat metabolism',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: '5-Amino-1MQ',
    description: 'NNMT inhibitor for fat loss and metabolism enhancement',
    category: 'Metabolic',
    benefits: 'Fat loss, Metabolism boost, Energy increase, Weight management, Body composition improvement',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once daily',
    timing: 'Morning optimal',
    administration_route: 'Oral',
  },
  {
    name: 'Tesofensine',
    description: 'Triple monoamine reuptake inhibitor for appetite suppression and fat loss',
    category: 'Metabolic',
    benefits: 'Appetite suppression, Fat loss, Weight reduction, Metabolic boost, Body composition improvement',
    side_effects: 'Mild nausea, Headache, Dizziness, Potential cardiovascular effects, Requires monitoring',
    dosage_min: '0.25 mg',
    dosage_max: '0.5 mg',
    frequency: 'Once daily',
    timing: 'Morning with food',
    administration_route: 'Oral',
  },
  {
    name: 'Adipotide',
    description: 'Targeted fat cell apoptosis peptide for selective fat reduction',
    category: 'Metabolic',
    benefits: 'Targeted fat loss, Fat cell reduction, Body composition improvement, Metabolic acceleration, Fat decrease',
    side_effects: 'Potential kidney effects, Requires medical monitoring, Caution advised, Not widely available, Experimental',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Three times weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'CJC-1295 + Ipamorelin',
    description: 'Synergistic fat loss combination of GHRH and GH secretagogue',
    category: 'Metabolic',
    benefits: 'Synergistic fat loss, GH stimulation, Muscle preservation, Metabolism boost, Body recomposition',
    side_effects: 'Mild flushing, Hunger increase, Headache, Hyperglycemia, Injection site reaction',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Tesamorelin',
    description: 'Visceral fat reduction through GHRH signaling for metabolic improvement',
    category: 'Metabolic',
    benefits: 'Visceral fat reduction, Metabolism improvement, Metabolic health, Cardiovascular benefits, Body composition',
    side_effects: 'Joint pain, Carpal tunnel syndrome, Hyperglycemia, Water retention, Headache',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHRP-2 + MOD-GRF',
    description: 'Fat loss and muscle preservation combination of GH secretagogue and GHRH',
    category: 'Metabolic',
    benefits: 'Fat loss, Muscle preservation, GH stimulation, Body recomposition, Metabolic improvement',
    side_effects: 'Appetite increase, Hyperglycemia, Water retention, Potential prolactin elevation, Headache',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },

  // Performance & Athletic (10+)
  {
    name: 'Follistatin 344',
    description: 'Myostatin inhibitor peptide for significant muscle growth without fat accumulation',
    category: 'Performance',
    benefits: 'Muscle growth, Myostatin inhibition, Strength increase, Lean mass gain, Athletic performance',
    side_effects: 'Mild joint pain, Potential systemic effects, Caution advised, Experimental status, Requires monitoring',
    dosage_min: '50 mcg',
    dosage_max: '100 mcg',
    frequency: 'Every other day',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'ACE-031',
    description: 'Myostatin and ActR2B inhibitor for muscle growth and strength gains',
    category: 'Performance',
    benefits: 'Muscle growth, Strength increase, Myostatin inhibition, Lean mass gain, Athletic enhancement',
    side_effects: 'Potential cardiovascular effects, Caution required, Experimental status, Requires monitoring, Rare systemic effects',
    dosage_min: '50 mcg',
    dosage_max: '100 mcg',
    frequency: 'Every other day',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'YK-11',
    description: 'Myostatin inhibitor SARM-like peptide for muscle building and strength',
    category: 'Performance',
    benefits: 'Muscle growth, Strength increase, Lean mass gain, Myostatin inhibition, Athletic performance',
    side_effects: 'Potential hormonal effects, Caution advised, May affect hormones, Requires monitoring, Experimental',
    dosage_min: '5 mg',
    dosage_max: '15 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Oral',
  },
  {
    name: 'Mechano Growth Factor (MGF)',
    description: 'IGF-1 variant supporting muscle repair and growth after training',
    category: 'Performance',
    benefits: 'Muscle repair, Growth stimulation, Recovery acceleration, Strength increase, Post-workout support',
    side_effects: 'Mild injection site reaction, Potential systemic effects, Generally well-tolerated, Rare effects, Safe profile',
    dosage_min: '200 mcg',
    dosage_max: '400 mcg',
    frequency: 'Two to three times weekly',
    timing: 'Post-workout optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'PEG-MGF',
    description: 'Pegylated MGF with extended half-life for longer lasting effects',
    category: 'Performance',
    benefits: 'Extended muscle growth support, Longer-lasting effects, Recovery enhancement, Strength increase, Athletic benefit',
    side_effects: 'Mild injection site reaction, Potential systemic effects, Generally well-tolerated, Rare effects, Safe',
    dosage_min: '100 mcg',
    dosage_max: '200 mcg',
    frequency: 'Once to twice weekly',
    timing: 'Any time of day',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'IGF-1 LR3',
    description: 'Long-acting insulin-like growth factor for sustained muscle growth and recovery',
    category: 'Performance',
    benefits: 'Extended muscle growth, Strength increase, Recovery enhancement, Lean mass gain, Athletic performance',
    side_effects: 'Hypoglycemia risk, Joint pain, Potential systemic effects, Requires monitoring, Caution advised',
    dosage_min: '50 mcg',
    dosage_max: '100 mcg',
    frequency: 'Once to twice daily',
    timing: 'Post-workout or any time',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'IGF-1 DES',
    description: 'Short-acting IGF-1 variant for rapid muscle building effects',
    category: 'Performance',
    benefits: 'Rapid muscle growth, Strength increase, Recovery acceleration, Athletic enhancement, Quick acting',
    side_effects: 'Hypoglycemia risk, Joint pain, Potential systemic effects, Requires careful dosing, Caution needed',
    dosage_min: '40 mcg',
    dosage_max: '80 mcg',
    frequency: 'Once to twice daily',
    timing: 'Post-workout optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'HGH Fragment 176-191',
    description: 'Performance-enhancing fragment without growth hormone receptor activation',
    category: 'Performance',
    benefits: 'Fat loss, Muscle preservation, Athletic performance, Body recomposition, Enhanced endurance',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '200 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Before cardio or bedtime',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Ipamorelin + CJC-1295',
    description: 'Performance enhancement stack combining GH secretagogue with GHRH',
    category: 'Performance',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Athletic performance, Body recomposition, Strength increase',
    side_effects: 'Mild flushing, Hunger increase, Headache, Hyperglycemia, Injection site reaction',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening and before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHRP-6 + CJC-1295',
    description: 'Muscle building combination of potent GH secretagogue with GHRH analog',
    category: 'Performance',
    benefits: 'Potent GH stimulation, Muscle growth, Strength increase, Athletic enhancement, Body recomposition',
    side_effects: 'Appetite increase, Water retention, Hyperglycemia, Potential cortisol elevation, Headache',
    dosage_min: '100 mcg',
    dosage_max: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals and before bed',
    administration_route: 'Subcutaneous',
  },

  // Anti-Aging & Longevity (10+)
  {
    name: 'Epitalon',
    description: 'Telomerase activator peptide for cellular age reversal and longevity',
    category: 'Anti-Aging',
    benefits: 'Telomerase activation, Cellular rejuvenation, Anti-aging effects, Longevity support, Age reversal',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Evening optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'GHK-Cu',
    description: 'Copper peptide for comprehensive anti-aging and tissue rejuvenation',
    category: 'Anti-Aging',
    benefits: 'Anti-aging effects, Skin rejuvenation, Collagen production, Tissue repair, Longevity support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '1 mg',
    dosage_max: '3 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Thymalin',
    description: 'Thymus extract peptide for immune system aging and cellular restoration',
    category: 'Anti-Aging',
    benefits: 'Immune aging reversal, Anti-aging effects, Immune restoration, Cellular support, Longevity',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Pinealon',
    description: 'Pineal gland peptide for sleep and aging clock regulation',
    category: 'Anti-Aging',
    benefits: 'Sleep improvement, Aging clock regulation, Melatonin enhancement, Anti-aging, Circadian support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '3 mg',
    dosage_max: '5 mg',
    frequency: 'Once daily',
    timing: 'Evening before bed',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Cortagen',
    description: 'Cardiovascular peptide supporting heart health and anti-aging',
    category: 'Anti-Aging',
    benefits: 'Cardiovascular support, Heart health, Anti-aging effects, Metabolic support, Longevity',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Vilon',
    description: 'Thymus peptide for immune aging reversal and longevity support',
    category: 'Anti-Aging',
    benefits: 'Immune restoration, Anti-aging effects, Longevity support, Cellular health, Age-related improvement',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Livagen',
    description: 'Liver protection peptide supporting hepatic function and longevity',
    category: 'Anti-Aging',
    benefits: 'Liver protection, Hepatic function support, Anti-aging, Detoxification support, Longevity',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Bronchogen',
    description: 'Respiratory system peptide supporting lung health and oxygen utilization',
    category: 'Anti-Aging',
    benefits: 'Respiratory support, Lung health, Oxygen utilization, Anti-aging effects, System support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Vesugen',
    description: 'Vascular system peptide supporting cardiovascular health and circulation',
    category: 'Anti-Aging',
    benefits: 'Vascular support, Circulation improvement, Cardiovascular health, Anti-aging, Blood flow',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Cerluten',
    description: 'Brain aging peptide supporting cognitive function and neuronal health',
    category: 'Anti-Aging',
    benefits: 'Brain aging reversal, Cognitive support, Neuroprotection, Anti-aging, Neuronal health',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '10 mg',
    dosage_max: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },

  // Immune & Inflammation (10+)
  {
    name: 'Thymosin Alpha-1',
    description: 'Immune system modulator supporting thymic function and immune response',
    category: 'Immune',
    benefits: 'Immune support, T-cell function, Thymic activation, Anti-aging effects, Immune recovery',
    side_effects: 'Minimal side effects, Well-tolerated, Rare injection site reaction, Generally safe, Few adverse events',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Three times weekly',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'LL-37',
    description: 'Antimicrobial peptide with immune modulation and anti-inflammatory effects',
    category: 'Immune',
    benefits: 'Antimicrobial activity, Immune modulation, Anti-inflammatory, Infection protection, Immune support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '100 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'As needed for immune support',
    administration_route: 'Topical',
  },
  {
    name: 'BPC-157',
    description: 'Immune-enhancing compound with anti-inflammatory and tissue-protective effects',
    category: 'Immune',
    benefits: 'Anti-inflammatory effects, Immune modulation, Tissue protection, Gut health, Injury recovery',
    side_effects: 'Generally well-tolerated, Rare mild headache, Minimal systemic effects, Few side effects, Safe',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'KPV',
    description: 'Anti-inflammatory tripeptide with immunomodulatory effects',
    category: 'Immune',
    benefits: 'Anti-inflammatory, Immune modulation, Gut protection, Reduced inflammation, Immune support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare headache, Generally safe, Few adverse events',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Intranasal',
  },
  {
    name: 'Thymulin',
    description: 'Thymus hormone for T-cell maturation and immune system function',
    category: 'Immune',
    benefits: 'T-cell function, Immune system support, Thymic hormone replacement, Immune maturation, Anti-aging',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '1 mg',
    dosage_max: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Splenopentin',
    description: 'Spleen-derived peptide for immune function enhancement',
    category: 'Immune',
    benefits: 'Immune enhancement, Spleen function, T-cell support, Infection resistance, Immune resilience',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Myelopid',
    description: 'Bone marrow-derived peptide supporting immune cell production',
    category: 'Immune',
    benefits: 'Immune cell production, Bone marrow support, Infection resistance, Immune recovery, Blood cell support',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Dalargin',
    description: 'Opioid peptide with immune-enhancing and anti-inflammatory properties',
    category: 'Immune',
    benefits: 'Pain relief, Anti-inflammatory, Immune modulation, Stress reduction, Gut protection',
    side_effects: 'Minimal side effects, Well-tolerated, Rare opioid-like effects, Generally safe, Few adverse events',
    dosage_min: '500 mcg',
    dosage_max: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'As needed for pain or immune support',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Deltaran',
    description: 'Anti-inflammatory peptide for immune modulation',
    category: 'Immune',
    benefits: 'Anti-inflammatory effects, Immune modulation, Inflammation reduction, Immune support, Recovery',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Vilon',
    description: 'T-cell function enhancer supporting immune system resilience',
    category: 'Immune',
    benefits: 'T-cell function, Immune enhancement, Anti-aging, System support, Cellular immunity',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe, Few adverse events',
    dosage_min: '5 mg',
    dosage_max: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },

  // Skin & Cosmetic (10+)
  {
    name: 'Matrixyl (Palmitoyl Pentapeptide)',
    description: 'Collagen-boosting peptide for skin firmness and anti-aging effects',
    category: 'Other',
    benefits: 'Collagen synthesis, Skin firmness, Anti-wrinkle, Anti-aging, Improved skin texture',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '2%',
    dosage_max: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Argireline',
    description: 'Botox-like wrinkle reducer without toxins for facial expression control',
    category: 'Other',
    benefits: 'Wrinkle reduction, Expression line reduction, Anti-aging, Skin smoothing, Natural appearance',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '3%',
    dosage_max: '10%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Copper Peptide GHK',
    description: 'Copper complex for skin healing and collagen production',
    category: 'Other',
    benefits: 'Collagen production, Skin healing, Anti-aging, Wound healing, Tissue regeneration',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '0.5%',
    dosage_max: '2%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Palmitoyl Tripeptide-1',
    description: 'Collagen-stimulating peptide for skin firmness enhancement',
    category: 'Other',
    benefits: 'Collagen production, Skin firmness, Elasticity improvement, Anti-aging, Lifting effect',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '0.3%',
    dosage_max: '3%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Palmitoyl Tetrapeptide-7',
    description: 'Anti-inflammatory peptide for sensitive skin and inflammation reduction',
    category: 'Other',
    benefits: 'Anti-inflammatory effects, Redness reduction, Sensitive skin support, Skin soothing, Calming',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '0.5%',
    dosage_max: '2%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Acetyl Hexapeptide-8',
    description: 'Wrinkle-reducing peptide mimicking botulinum toxin mechanism naturally',
    category: 'Other',
    benefits: 'Wrinkle reduction, Expression line reduction, Anti-aging, Skin smoothing, Natural lifting',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '2%',
    dosage_max: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Tripeptide-10 Citrulline',
    description: 'Collagen support peptide for skin firmness and elasticity',
    category: 'Other',
    benefits: 'Collagen support, Skin elasticity, Firmness improvement, Anti-aging, Skin texture improvement',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '2%',
    dosage_max: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Palmitoyl Oligopeptide',
    description: 'Skin firmness and texture improvement peptide',
    category: 'Other',
    benefits: 'Skin firmness, Texture improvement, Anti-aging, Elasticity enhancement, Lifting effect',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '2%',
    dosage_max: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Syn-Coll',
    description: 'Collagen synthesis promoter for anti-aging and skin rejuvenation',
    category: 'Other',
    benefits: 'Collagen synthesis, Anti-aging, Skin rejuvenation, Firmness improvement, Elasticity enhancement',
    side_effects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe, Few adverse events',
    dosage_min: '2%',
    dosage_max: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },
  {
    name: 'Peptide Eye Contour',
    description: 'Specialized peptide complex for delicate eye area and wrinkle reduction',
    category: 'Other',
    benefits: 'Wrinkle reduction, Eye area firmness, Dark circle reduction, Anti-aging, Skin elasticity',
    side_effects: 'Minimal side effects, Well-tolerated, Rare eye irritation, Generally safe, Few adverse events',
    dosage_min: '1%',
    dosage_max: '3%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Topical',
  },

  // Additional Specialized (5+)
  {
    name: 'Melanotan II',
    description: 'Tanning peptide and libido enhancer with melanocyte-stimulating effects',
    category: 'Other',
    benefits: 'Tanning effects, Skin darkening, Libido enhancement, Sexual function improvement, Appetite suppression',
    side_effects: 'Nausea, Facial flushing, Spontaneous erections, Moles darkening, Vomiting possible',
    dosage_min: '250 mcg',
    dosage_max: '500 mcg',
    frequency: 'Daily or every other day',
    timing: 'Evening optimal',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'PT-141 (Bremelanotide)',
    description: 'Sexual dysfunction treatment with melanocortin receptor activation',
    category: 'Other',
    benefits: 'Sexual function improvement, Erectile function, Female sexual arousal, Libido enhancement, Sexual response',
    side_effects: 'Facial flushing, Nausea, Headache, Potential systemic effects, Requires medical supervision',
    dosage_min: '0.3 mg',
    dosage_max: '1.7 mg',
    frequency: 'As needed',
    timing: '45 minutes before sexual activity',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Kisspeptin-10',
    description: 'Reproductive hormone regulator for fertility and sexual function',
    category: 'Other',
    benefits: 'Reproductive hormone regulation, Fertility support, Sexual function, Hormone balance, Reproductive health',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '50 mcg',
    dosage_max: '100 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Gonadorelin',
    description: 'GnRH peptide for fertility support and reproductive hormone regulation',
    category: 'Other',
    benefits: 'Fertility support, Reproductive hormone balance, Testosterone production, Sexual function, Hormone regulation',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '25 mcg',
    dosage_max: '100 mcg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
  {
    name: 'Oxytocin',
    description: 'Social bonding and trust hormone with relationship and mood benefits',
    category: 'Other',
    benefits: 'Social bonding, Trust enhancement, Mood improvement, Relationship support, Emotional connection',
    side_effects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe, Few adverse events',
    dosage_min: '2 IU',
    dosage_max: '10 IU',
    frequency: 'Once to twice daily',
    timing: 'Morning or evening',
    administration_route: 'Subcutaneous',
  },
];

try {
  app.logger.info({ count: peptideData.length }, 'Starting peptide database seed');

  for (const peptide of peptideData) {
    await app.db.insert(schema.peptides).values(peptide);
  }

  app.logger.info({ count: peptideData.length }, 'Successfully seeded peptides');
  process.exit(0);
} catch (error) {
  app.logger.error({ err: error }, 'Failed to seed peptides');
  process.exit(1);
}
