export const peptideSeedData = [
  // GLP-1 Agonists (10)
  {
    name: 'Semaglutide',
    description: 'GLP-1 receptor agonist for weight management and blood sugar control with long-acting effects',
    category: 'GLP-1',
    benefits: 'Weight loss, Blood sugar control, Appetite suppression, Cardiovascular protection, Sustained satiety',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Injection site reactions',
    dosageMin: '0.25 mg',
    dosageMax: '2.4 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL of bacteriostatic water to the 2 mg or 2.4 mg vial. Gently swirl until completely dissolved. Do not shake. Store in refrigerator between 2-8°C.',
  },
  {
    name: 'Tirzepatide',
    description: 'Dual GIP/GLP-1 receptor agonist for diabetes and weight loss with synergistic effects',
    category: 'GLP-1',
    benefits: 'Superior weight loss, Blood sugar control, Dual mechanism, Increased insulin sensitivity, Sustained benefit',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Injection site irritation',
    dosageMin: '2.5 mg',
    dosageMax: '15 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL of bacteriostatic water to the 5 mg or 10 mg vial. Gently swirl until fully dissolved. Do not shake. Refrigerate between 2-8°C after reconstitution.',
  },
  {
    name: 'Liraglutide',
    description: 'GLP-1 analog for type 2 diabetes and obesity with once or twice daily dosing',
    category: 'GLP-1',
    benefits: 'Weight loss, Blood sugar management, Cardiovascular benefits, Appetite reduction, Improved glycemic control',
    sideEffects: 'Nausea, Headache, Diarrhea, Vomiting, Constipation',
    dosageMin: '0.6 mg',
    dosageMax: '3.0 mg',
    frequency: 'Once or twice daily',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Available as pre-filled pen or vial. If vial, add 1 mL bacteriostatic water. Allow to dissolve naturally. Store at 2-8°C.',
  },
  {
    name: 'Dulaglutide',
    description: 'Long-acting GLP-1 receptor agonist with extended half-life for weekly dosing',
    category: 'GLP-1',
    benefits: 'Weight reduction, Blood glucose control, Cardiovascular protection, Consistent levels, Long-acting',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosageMin: '0.75 mg',
    dosageMax: '4.5 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Available as pre-filled pen. No reconstitution required. Store in refrigerator at 2-8°C until use.',
  },
  {
    name: 'Exenatide',
    description: 'GLP-1 mimetic for blood glucose control with short or extended-release formulations',
    category: 'GLP-1',
    benefits: 'Blood sugar control, Weight loss, Multiple injection options, Appetite suppression, Proven efficacy',
    sideEffects: 'Nausea, Vomiting, Hypoglycemia, Headache, Weakness',
    dosageMin: '5 mcg',
    dosageMax: '10 mcg',
    frequency: 'Twice daily or once weekly',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'For extended-release, add 0.6 mL of supplied diluent to vial. For immediate-release, typically available as pre-filled pens. No additional reconstitution needed.',
  },
  {
    name: 'Albiglutide',
    description: 'Weekly GLP-1 receptor agonist with extended duration of action for diabetes management',
    category: 'GLP-1',
    benefits: 'Weekly dosing, Blood sugar control, Weight reduction, Cardiovascular effects, Simplified regimen',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosageMin: '30 mg',
    dosageMax: '50 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Available as pre-filled pen. No reconstitution needed. Refrigerate at 2-8°C until use.',
  },
  {
    name: 'Lixisenatide',
    description: 'Short-acting GLP-1 receptor agonist with rapid onset for meal-time glucose control',
    category: 'GLP-1',
    benefits: 'Rapid onset, Blood sugar control, Weight reduction, Meal-time dosing, Safety profile',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosageMin: '10 mcg',
    dosageMax: '20 mcg',
    frequency: 'Once daily',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Available as pre-filled injection pen. No reconstitution required. Store at 2-8°C.',
  },
  {
    name: 'Retatrutide',
    description: 'Triple agonist combining GLP-1, GIP, and glucagon receptor signaling for superior weight loss',
    category: 'GLP-1',
    benefits: 'Superior weight loss, Metabolic improvement, Glucose control, Enhanced lipid profile, Triple mechanism',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Injection site reactions, Gastrointestinal effects',
    dosageMin: '1 mg',
    dosageMax: '8 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to the vial. Swirl gently until completely dissolved. Do not shake. Refrigerate at 2-8°C.',
  },
  {
    name: 'CagriSema',
    description: 'Combination of cagrilintide and semaglutide for enhanced synergistic weight loss effects',
    category: 'GLP-1',
    benefits: 'Synergistic weight loss, Blood sugar control, Dual mechanism, Enhanced satiety, Improved compliance',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Gastrointestinal effects',
    dosageMin: '0.25 mg',
    dosageMax: '2.4 mg',
    frequency: 'Once weekly',
    timing: 'Any time of day',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL of bacteriostatic water. Allow to dissolve naturally by gentle swirling. Store at 2-8°C.',
  },
  {
    name: 'Semaglutide (Oral)',
    description: 'First oral GLP-1 receptor agonist with absorption enhancer for convenient daily dosing',
    category: 'GLP-1',
    benefits: 'Oral administration, Weight loss, Blood sugar control, No injections, Improved compliance',
    sideEffects: 'Nausea, Vomiting, Diarrhea, Constipation, Headache',
    dosageMin: '3 mg',
    dosageMax: '14 mg',
    frequency: 'Once daily',
    timing: 'Morning on empty stomach',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Use tablets as directed with water on an empty stomach, at least 30 minutes before food.',
  },

  // Growth Hormone Peptides (20)
  {
    name: 'Ipamorelin',
    description: 'Selective GH secretagogue with minimal side effects and excellent safety profile',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Improved sleep, Minimal cortisol elevation',
    sideEffects: 'Mild hunger increase, Slight hyperglycemia, Rare flushing, Minimal side effects',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening optimal',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Allow 1-2 minutes for dissolution. Store at 2-8°C.',
  },
  {
    name: 'CJC-1295',
    description: 'GHRH analog for stimulating natural growth hormone release with long-acting properties',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Anti-aging effects, Improved recovery',
    sideEffects: 'Flushing, Headache, Dizziness, Hunger increase, Hyperglycemia',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Three times weekly',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Swirl gently until dissolved. Do not shake. Refrigerate at 2-8°C.',
  },
  {
    name: 'GHRP-2',
    description: 'Growth hormone releasing peptide with dual signaling for potent GH stimulation',
    category: 'Growth Hormone',
    benefits: 'Powerful GH release, Appetite stimulation, Muscle growth support, Improved sleep, Synergistic effects',
    sideEffects: 'Appetite increase, Water retention, Hyperglycemia, Prolactin elevation, Potential tolerance',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently by swirling. Store refrigerated at 2-8°C.',
  },
  {
    name: 'GHRP-6',
    description: 'GH secretagogue with pronounced appetite stimulation and strong GH release effects',
    category: 'Growth Hormone',
    benefits: 'Potent GH release, Strong appetite stimulation, Muscle growth, Improved recovery, Enhanced signaling',
    sideEffects: 'Significant appetite increase, Water retention, Hyperglycemia, Potential tolerance, Cortisol elevation',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Allow 2-3 minutes for complete dissolution. Refrigerate at 2-8°C.',
  },
  {
    name: 'Hexarelin',
    description: 'Potent GH releasing peptide with strong growth hormone secretion properties',
    category: 'Growth Hormone',
    benefits: 'Strong GH stimulation, Muscle building, Cardiovascular tone, Anti-aging effects, Potent secretagogue',
    sideEffects: 'Cortisol elevation, Potential prolactin increase, Hyperglycemia, Possible tolerance, Water retention',
    dosageMin: '100 mcg',
    dosageMax: '200 mcg',
    frequency: 'Daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Swirl gently, do not shake. Store at 2-8°C.',
  },
  {
    name: 'Sermorelin',
    description: 'GHRH analog for stimulating natural GH production with physiological effects',
    category: 'Growth Hormone',
    benefits: 'Natural GH stimulation, Muscle growth, Fat loss, Improved sleep quality, Anti-aging benefits',
    sideEffects: 'Mild headache, Flushing, Nausea, Water retention, Mild hyperglycemia',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Once daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 15 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C after reconstitution.',
  },
  {
    name: 'Tesamorelin',
    description: 'GHRH analog specifically for reducing visceral fat and improving body composition',
    category: 'Growth Hormone',
    benefits: 'Visceral fat reduction, Body composition improvement, Metabolic improvement, Cardiovascular benefits',
    sideEffects: 'Joint pain, Carpal tunnel syndrome, Hyperglycemia, Water retention, Headache',
    dosageMin: '1 mg',
    dosageMax: '2 mg',
    frequency: 'Once daily',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Allow 1 minute for dissolution. Do not shake. Store at 2-8°C.',
  },
  {
    name: 'MK-677 (Ibutamoren)',
    description: 'Oral GH secretagogue and ghrelin mimetic with non-peptide structure for convenience',
    category: 'Growth Hormone',
    benefits: 'Oral administration, GH stimulation, Appetite increase, Muscle growth, Improved sleep',
    sideEffects: 'Increased appetite, Water retention, Hyperglycemia, Mild headache, Potential prolactin elevation',
    dosageMin: '10 mg',
    dosageMax: '25 mg',
    frequency: 'Once daily',
    timing: 'Evening',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take capsules with water as directed.',
  },
  {
    name: 'AOD-9604',
    description: 'Anti-obesity peptide fragment for targeted fat loss without growth hormone effects',
    category: 'Growth Hormone',
    benefits: 'Fat loss, Metabolism boost, Body composition improvement, No GH side effects, Lipolysis promotion',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe profile',
    dosageMin: '300 mcg',
    dosageMax: '600 mcg',
    frequency: 'Once to twice daily',
    timing: 'Before cardio',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently until clear. Store at 2-8°C.',
  },
  {
    name: 'Fragment 176-191',
    description: 'HGH fragment specifically designed for fat loss without growth hormone receptor activation',
    category: 'Growth Hormone',
    benefits: 'Fat loss, Metabolism acceleration, Body composition improvement, Lipolysis, No muscle loss',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe',
    dosageMin: '200 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Before cardio',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Allow 1-2 minutes for complete dissolution. Refrigerate at 2-8°C.',
  },
  {
    name: 'IGF-1 LR3',
    description: 'Long-acting insulin-like growth factor for sustained muscle growth and recovery',
    category: 'Growth Hormone',
    benefits: 'Extended muscle growth, Strength increase, Recovery enhancement, Lean mass gain, Athletic performance',
    sideEffects: 'Hypoglycemia risk, Joint pain, Potential systemic effects, Requires monitoring',
    dosageMin: '50 mcg',
    dosageMax: '100 mcg',
    frequency: 'Once to twice daily',
    timing: 'Post-workout',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Mix by gentle swirling. Store at 2-8°C. Use within 30 days of reconstitution.',
  },
  {
    name: 'IGF-1 DES',
    description: 'Short-acting IGF-1 variant for rapid muscle building and recovery effects',
    category: 'Growth Hormone',
    benefits: 'Rapid muscle growth, Strength increase, Recovery acceleration, Quick acting, Local effects',
    sideEffects: 'Hypoglycemia risk, Joint pain, Potential systemic effects, Requires careful dosing',
    dosageMin: '40 mcg',
    dosageMax: '80 mcg',
    frequency: 'Once to twice daily',
    timing: 'Post-workout',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Swirl gently until dissolved. Refrigerate at 2-8°C.',
  },
  {
    name: 'Follistatin 344',
    description: 'Myostatin inhibitor peptide for significant muscle growth without fat accumulation',
    category: 'Growth Hormone',
    benefits: 'Muscle growth, Myostatin inhibition, Strength increase, Lean mass gain, Athletic performance',
    sideEffects: 'Mild joint pain, Potential systemic effects, Caution advised, Experimental status',
    dosageMin: '50 mcg',
    dosageMax: '100 mcg',
    frequency: 'Every other day',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Allow 2 minutes for dissolution. Do not shake vigorously. Store at 2-8°C.',
  },
  {
    name: 'TB-500 (Thymosin Beta-4)',
    description: 'Powerful healing peptide promoting tissue repair and muscle recovery effects',
    category: 'Growth Hormone',
    benefits: 'Rapid healing, Tissue regeneration, Muscle repair, Anti-inflammatory, Improved recovery',
    sideEffects: 'Headache, Mild nausea, Dizziness, Rare light sensitivity, Generally well-tolerated',
    dosageMin: '2 mg',
    dosageMax: '4 mg',
    frequency: 'Once to twice weekly',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 0.6 mL bacteriostatic water to 5 mg vial. Swirl gently for 1 minute. Store at 2-8°C.',
  },
  {
    name: 'MOD GRF 1-29',
    description: 'Modified GRF peptide for enhanced GH release with reduced side effects',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Anti-aging, Improved recovery',
    sideEffects: 'Mild flushing, Headache, Hunger increase, Hyperglycemia, Dizziness',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening optimal',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix gently by swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'GHRP-1',
    description: 'GH releasing peptide with selective growth hormone stimulation and minimal side effects',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Fat loss, Reduced side effects, Enhanced recovery',
    sideEffects: 'Mild hunger increase, Slight hyperglycemia, Rare flushing, Minimal systemic effects',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Allow 1-2 minutes for dissolution. Store at 2-8°C.',
  },
  {
    name: 'Pralmorelin',
    description: 'GH secretagogue peptide for natural growth hormone stimulation and muscle development',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Strength increase, Fat loss, Anti-aging effects',
    sideEffects: 'Mild flushing, Headache, Hyperglycemia, Appetite increase, Dizziness',
    dosageMin: '100 mcg',
    dosageMax: '200 mcg',
    frequency: 'Daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix gently. Do not shake. Refrigerate at 2-8°C.',
  },
  {
    name: 'CJC-1293',
    description: 'DAC-free GHRH analog with extended half-life for convenient dosing',
    category: 'Growth Hormone',
    benefits: 'Natural GH stimulation, Muscle growth, Fat loss, Anti-aging, Improved sleep',
    sideEffects: 'Flushing, Headache, Hunger increase, Hyperglycemia, Water retention',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Two to three times weekly',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Swirl gently until completely dissolved. Store at 2-8°C.',
  },
  {
    name: 'Alexamorelin',
    description: 'GH secretagogue with selective growth hormone release and excellent tolerability',
    category: 'Growth Hormone',
    benefits: 'GH stimulation, Muscle growth, Recovery enhancement, Fat loss, Anti-aging effects',
    sideEffects: 'Mild hunger increase, Slight hyperglycemia, Rare flushing, Minimal side effects',
    dosageMin: '100 mcg',
    dosageMax: '200 mcg',
    frequency: 'Daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Allow 1 minute for dissolution. Refrigerate at 2-8°C.',
  },

  // Healing & Recovery Peptides (18)
  {
    name: 'BPC-157',
    description: 'Body protection compound for rapid tissue repair and healing of injuries',
    category: 'Healing',
    benefits: 'Tissue repair, Muscle recovery, Joint healing, Anti-inflammatory, Improved healing speed',
    sideEffects: 'Generally well-tolerated, Rare mild headache, Minimal systemic effects, Safe profile',
    dosageMin: '250 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently by swirling. Store at 2-8°C.',
  },
  {
    name: 'GHK-Cu',
    description: 'Copper peptide for wound healing, skin rejuvenation, and comprehensive tissue repair',
    category: 'Healing',
    benefits: 'Wound healing, Skin rejuvenation, Collagen production, Anti-aging, Tissue restoration',
    sideEffects: 'Minimal side effects, Rare skin irritation, Occasional taste disturbance, Well-tolerated',
    dosageMin: '1 mg',
    dosageMax: '3 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Epithalon',
    description: 'Telomerase activator peptide for longevity and cellular age reversal',
    category: 'Anti-Aging',
    benefits: 'Telomerase activation, Anti-aging, Cellular rejuvenation, Longevity support, Age reversal',
    sideEffects: 'Minimal side effects, Rare headache, Generally well-tolerated, Safe long-term use',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Swirl gently until dissolved. Store at 2-8°C.',
  },
  {
    name: 'Selank',
    description: 'Anxiolytic and nootropic peptide with anti-anxiety and cognitive benefits',
    category: 'Cognitive',
    benefits: 'Anxiety reduction, Cognitive enhancement, Anti-stress, Mood improvement, Neuroprotection',
    sideEffects: 'Minimal side effects, Rare headache, Occasional mild dizziness, Generally safe',
    dosageMin: '250 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and afternoon',
    administrationRoute: 'Intranasal',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Store at 2-8°C. Use as intranasal spray.',
  },
  {
    name: 'Semax',
    description: 'Nootropic peptide for cognitive enhancement and neuroprotection without addiction',
    category: 'Cognitive',
    benefits: 'Cognitive enhancement, Memory improvement, Neuroprotection, Stress resilience, Brain support',
    sideEffects: 'Minimal side effects, Rare headache, Mild insomnia if dosed late, Generally safe',
    dosageMin: '50 mcg',
    dosageMax: '200 mcg',
    frequency: 'Once to three times daily',
    timing: 'Morning and afternoon',
    administrationRoute: 'Intranasal',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently. Refrigerate at 2-8°C. Apply as intranasal drops.',
  },
  {
    name: 'Cerebrolysin',
    description: 'Neurotrophic peptide mixture supporting brain function and neuroprotection',
    category: 'Cognitive',
    benefits: 'Neuroprotection, Brain cell support, Cognitive enhancement, Stroke recovery, Memory improvement',
    sideEffects: 'Mild headache, Rare dizziness, Nausea, Injection site irritation, Generally safe',
    dosageMin: '5 mL',
    dosageMax: '10 mL',
    frequency: 'Daily or three times weekly',
    timing: 'Morning',
    administrationRoute: 'Intramuscular',
    reconstitutionInstructions: 'Available as pre-filled ampoules or vials. No reconstitution required. Use as directed by healthcare provider.',
  },
  {
    name: 'P21',
    description: 'Cognitive enhancer derived from CNTF with neuroprotective effects',
    category: 'Cognitive',
    benefits: 'Cognitive enhancement, Neuroprotection, Memory improvement, Brain cell support, Neural preservation',
    sideEffects: 'Mild headache, Rare dizziness, Minimal side effects, Generally well-tolerated',
    dosageMin: '100 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning',
    administrationRoute: 'Intranasal',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently. Store at 2-8°C. Apply as intranasal spray.',
  },
  {
    name: 'Dihexa',
    description: 'Cognitive enhancer and neurogenesis promoter with brain-derived neurotrophic factor effects',
    category: 'Cognitive',
    benefits: 'Neurogenesis promotion, Cognitive enhancement, Neuroprotection, Memory improvement, Brain growth',
    sideEffects: 'Mild headache, Rare dizziness, Generally well-tolerated, Minimal systemic effects',
    dosageMin: '100 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once daily',
    timing: 'Morning',
    administrationRoute: 'Intranasal',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'NSI-189',
    description: 'Neurogenesis stimulator supporting brain cell generation for mood improvement',
    category: 'Cognitive',
    benefits: 'Neurogenesis promotion, Mood improvement, Cognitive enhancement, Depression support, Brain growth',
    sideEffects: 'Mild headache, Rare dizziness, Generally well-tolerated, Few side effects',
    dosageMin: '40 mg',
    dosageMax: '80 mg',
    frequency: 'Once daily',
    timing: 'Morning',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take capsules with water as directed.',
  },
  {
    name: 'Noopept',
    description: 'Cognitive enhancer and neuroprotectant with brain-derived neurotrophic factor effects',
    category: 'Cognitive',
    benefits: 'Cognitive enhancement, Memory improvement, Neuroprotection, Focus improvement, Learning',
    sideEffects: 'Minimal side effects, Rare headache, Mild insomnia, Generally well-tolerated',
    dosageMin: '10 mg',
    dosageMax: '30 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and afternoon',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take capsules with water. Best taken on an empty stomach or with light meal.',
  },
  {
    name: 'Cortexin',
    description: 'Neuroprotective peptide complex supporting cognitive function and brain health',
    category: 'Cognitive',
    benefits: 'Neuroprotection, Cognitive support, Memory enhancement, Brain function, Anti-stress',
    sideEffects: 'Minimal side effects, Rare headache, Well-tolerated, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Pinealon',
    description: 'Pineal gland peptide supporting sleep quality and circadian rhythm regulation',
    category: 'Anti-Aging',
    benefits: 'Sleep support, Circadian regulation, Melatonin enhancement, Cognitive preservation, Anti-aging',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe',
    dosageMin: '3 mg',
    dosageMax: '5 mg',
    frequency: 'Once daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Thymalin',
    description: 'Thymus extract peptide for immune system aging reversal and cellular restoration',
    category: 'Immune',
    benefits: 'Immune aging reversal, Anti-aging effects, Immune restoration, Cellular support, Longevity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'KPV',
    description: 'Anti-inflammatory tripeptide with immunomodulatory and gut-protective effects',
    category: 'Healing',
    benefits: 'Anti-inflammatory, Gut healing, Immune modulation, Reduced inflammation, Intestinal support',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare headache, Generally safe',
    dosageMin: '250 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Intranasal',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Store at 2-8°C. Use as intranasal spray.',
  },
  {
    name: 'ARA-290',
    description: 'Tissue protective peptide with regenerative and neuroprotective properties',
    category: 'Healing',
    benefits: 'Tissue protection, Neuroprotection, Pain reduction, Tissue repair, Regenerative effects',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe',
    dosageMin: '500 mcg',
    dosageMax: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix gently until clear. Refrigerate at 2-8°C.',
  },
  {
    name: 'DSIP',
    description: 'Sleep-inducing peptide supporting natural sleep cycles and recovery',
    category: 'Healing',
    benefits: 'Sleep induction, Sleep quality improvement, Stress reduction, Recovery support, Natural sleep',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '500 mcg',
    dosageMax: '2 mg',
    frequency: 'Once daily',
    timing: 'Evening before bed',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Store at 2-8°C.',
  },

  // Skin & Cosmetic Peptides (18)
  {
    name: 'Melanotan II',
    description: 'Tanning peptide and libido enhancer with melanocyte-stimulating effects',
    category: 'Skin & Cosmetic',
    benefits: 'Tanning effects, Skin darkening, Libido enhancement, Sexual function improvement, Appetite suppression',
    sideEffects: 'Nausea, Facial flushing, Spontaneous erections, Moles darkening, Vomiting possible',
    dosageMin: '250 mcg',
    dosageMax: '500 mcg',
    frequency: 'Daily or every other day',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by gentle swirling. Store at 2-8°C. Protect from light.',
  },
  {
    name: 'PT-141 (Bremelanotide)',
    description: 'Sexual dysfunction treatment with melanocortin receptor activation',
    category: 'Skin & Cosmetic',
    benefits: 'Sexual function improvement, Erectile function, Female sexual arousal, Libido enhancement',
    sideEffects: 'Facial flushing, Nausea, Headache, Potential systemic effects, Requires supervision',
    dosageMin: '0.3 mg',
    dosageMax: '1.7 mg',
    frequency: 'As needed',
    timing: '45 minutes before sexual activity',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C protected from light.',
  },
  {
    name: 'Melanotan I',
    description: 'Natural tanning peptide with melanocyte stimulation for sun-like effects',
    category: 'Skin & Cosmetic',
    benefits: 'Tanning effects, Skin protection, Skin darkening, UV protection, Natural appearance',
    sideEffects: 'Nausea, Facial flushing, Darkening of moles, Possible systemic effects',
    dosageMin: '500 mcg',
    dosageMax: '1 mg',
    frequency: 'Every other day',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by gentle swirling. Store at 2-8°C in darkness.',
  },
  {
    name: 'Matrixyl (Palmitoyl Pentapeptide)',
    description: 'Collagen-boosting peptide for skin firmness and anti-aging effects',
    category: 'Skin & Cosmetic',
    benefits: 'Collagen synthesis, Skin firmness, Anti-wrinkle, Anti-aging, Improved skin texture',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical serum or cream directly to clean skin.',
  },
  {
    name: 'Argireline',
    description: 'Botox-like wrinkle reducer without toxins for facial expression control',
    category: 'Skin & Cosmetic',
    benefits: 'Wrinkle reduction, Expression line reduction, Anti-aging, Skin smoothing, Natural appearance',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '3%',
    dosageMax: '10%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical cream to face twice daily.',
  },
  {
    name: 'Copper Peptide GHK',
    description: 'Copper complex for skin healing and collagen production enhancement',
    category: 'Skin & Cosmetic',
    benefits: 'Collagen production, Skin healing, Anti-aging, Wound healing, Tissue regeneration',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '0.5%',
    dosageMax: '2%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical serum to clean skin twice daily.',
  },
  {
    name: 'Palmitoyl Tripeptide-1',
    description: 'Collagen-stimulating peptide for skin firmness enhancement and elasticity',
    category: 'Skin & Cosmetic',
    benefits: 'Collagen production, Skin firmness, Elasticity improvement, Anti-aging, Lifting effect',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '0.3%',
    dosageMax: '3%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical serum to face and neck.',
  },
  {
    name: 'Palmitoyl Tetrapeptide-7',
    description: 'Anti-inflammatory peptide for sensitive skin and inflammation reduction',
    category: 'Skin & Cosmetic',
    benefits: 'Anti-inflammatory, Redness reduction, Sensitive skin support, Skin soothing, Calming',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '0.5%',
    dosageMax: '2%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply serum to sensitive areas twice daily.',
  },
  {
    name: 'Acetyl Hexapeptide-8',
    description: 'Wrinkle-reducing peptide mimicking botulinum toxin mechanism naturally',
    category: 'Skin & Cosmetic',
    benefits: 'Wrinkle reduction, Expression line reduction, Anti-aging, Skin smoothing, Natural lifting',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical cream to forehead and eye area.',
  },
  {
    name: 'Tripeptide-10 Citrulline',
    description: 'Collagen support peptide for skin firmness and elasticity improvement',
    category: 'Skin & Cosmetic',
    benefits: 'Collagen support, Skin elasticity, Firmness improvement, Anti-aging, Texture improvement',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply serum to face and neck twice daily.',
  },
  {
    name: 'Palmitoyl Oligopeptide',
    description: 'Skin firmness and texture improvement peptide for anti-aging',
    category: 'Skin & Cosmetic',
    benefits: 'Skin firmness, Texture improvement, Anti-aging, Elasticity enhancement, Lifting',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical serum to face daily.',
  },
  {
    name: 'Syn-Coll',
    description: 'Collagen synthesis promoter for anti-aging and skin rejuvenation',
    category: 'Skin & Cosmetic',
    benefits: 'Collagen synthesis, Anti-aging, Skin rejuvenation, Firmness improvement, Elasticity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply serum to face and neck.',
  },
  {
    name: 'Peptide Eye Contour',
    description: 'Specialized peptide complex for delicate eye area and wrinkle reduction',
    category: 'Skin & Cosmetic',
    benefits: 'Wrinkle reduction, Eye area firmness, Dark circle reduction, Anti-aging, Skin elasticity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare eye irritation, Generally safe',
    dosageMin: '1%',
    dosageMax: '3%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply eye cream around orbital area twice daily.',
  },
  {
    name: 'Palmitoyl Tripeptide-5',
    description: 'Growth factor-mimicking peptide for skin regeneration and rejuvenation',
    category: 'Skin & Cosmetic',
    benefits: 'Skin regeneration, Collagen enhancement, Anti-aging, Firmness improvement, Elasticity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '1%',
    dosageMax: '3%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply serum to face and neck twice daily.',
  },
  {
    name: 'Palmitoyl Dipeptide-5',
    description: 'Anti-inflammatory and skin-firming peptide for sensitive skin care',
    category: 'Skin & Cosmetic',
    benefits: 'Skin firming, Anti-inflammatory, Sensitive skin support, Redness reduction, Soothing',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '0.5%',
    dosageMax: '2%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply serum to sensitive areas daily.',
  },
  {
    name: 'Lipopeptide Complex',
    description: 'Advanced peptide complex for comprehensive skin rejuvenation and lifting',
    category: 'Skin & Cosmetic',
    benefits: 'Comprehensive rejuvenation, Skin lifting, Anti-aging, Firmness, Elasticity improvement',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply luxury serum to face twice daily.',
  },
  {
    name: 'Hexapeptide-9',
    description: 'Advanced wrinkle reduction peptide with enhanced skin smoothing properties',
    category: 'Skin & Cosmetic',
    benefits: 'Advanced wrinkle reduction, Expression control, Anti-aging, Skin smoothing, Lifting',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '2%',
    dosageMax: '5%',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply cream to target areas twice daily.',
  },

  // Immune Peptides (6)
  {
    name: 'Thymosin Alpha-1',
    description: 'Immune system modulator supporting thymic function and immune response',
    category: 'Immune',
    benefits: 'Immune support, T-cell function, Thymic activation, Anti-aging effects, Immune recovery',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare injection site reaction, Generally safe',
    dosageMin: '1 mg',
    dosageMax: '2 mg',
    frequency: 'Three times weekly',
    timing: 'Morning or evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix gently until dissolved. Store at 2-8°C.',
  },
  {
    name: 'LL-37',
    description: 'Antimicrobial peptide with wound healing and immune modulation properties',
    category: 'Immune',
    benefits: 'Antimicrobial activity, Wound healing, Anti-inflammatory, Infection protection, Immune support',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare skin irritation, Generally safe',
    dosageMin: '100 mcg',
    dosageMax: '500 mcg',
    frequency: 'Once to twice daily',
    timing: 'As needed',
    administrationRoute: 'Topical',
    reconstitutionInstructions: 'No reconstitution required. Apply topical cream to affected areas as needed.',
  },
  {
    name: 'Vilon',
    description: 'Thymus peptide for immune aging reversal and longevity support',
    category: 'Immune',
    benefits: 'Immune restoration, Anti-aging effects, Longevity support, Cellular health, Immune enhancement',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Splenopentin',
    description: 'Spleen-derived peptide for immune function enhancement',
    category: 'Immune',
    benefits: 'Immune enhancement, Spleen function, T-cell support, Infection resistance, Immune resilience',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Myelopid',
    description: 'Bone marrow-derived peptide supporting immune cell production',
    category: 'Immune',
    benefits: 'Immune cell production, Bone marrow support, Infection resistance, Immune recovery',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Two to three times daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently by swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Deltaran',
    description: 'Anti-inflammatory peptide for immune modulation and inflammation reduction',
    category: 'Immune',
    benefits: 'Anti-inflammatory, Immune modulation, Inflammation reduction, Immune support, Recovery',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix gently. Store at 2-8°C.',
  },

  // Metabolic & Performance (12)
  {
    name: 'MOTS-c',
    description: 'Mitochondrial-derived peptide improving metabolism and metabolic health',
    category: 'Metabolic',
    benefits: 'Metabolism improvement, Mitochondrial function, Fat loss, Insulin sensitivity, Metabolic health',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Humanin',
    description: 'Mitochondrial-derived peptide supporting metabolic and cellular health',
    category: 'Metabolic',
    benefits: 'Metabolic support, Cellular health, Anti-aging, Mitochondrial function, Fat metabolism',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '5 mg',
    dosageMax: '10 mg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: '5-Amino-1MQ',
    description: 'NNMT inhibitor for fat loss and metabolism enhancement',
    category: 'Metabolic',
    benefits: 'Fat loss, Metabolism boost, Energy increase, Weight management, Body composition improvement',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once daily',
    timing: 'Morning',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take capsules with water in the morning.',
  },
  {
    name: 'Tesofensine',
    description: 'Triple monoamine reuptake inhibitor for appetite suppression and fat loss',
    category: 'Metabolic',
    benefits: 'Appetite suppression, Fat loss, Weight reduction, Metabolic boost, Body composition',
    sideEffects: 'Mild nausea, Headache, Dizziness, Potential cardiovascular effects, Requires monitoring',
    dosageMin: '0.25 mg',
    dosageMax: '0.5 mg',
    frequency: 'Once daily',
    timing: 'Morning with food',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take tablet with breakfast.',
  },
  {
    name: 'Adipotide',
    description: 'Targeted fat cell apoptosis peptide for selective fat reduction',
    category: 'Metabolic',
    benefits: 'Targeted fat loss, Fat cell reduction, Body composition improvement, Metabolic acceleration',
    sideEffects: 'Potential kidney effects, Requires medical monitoring, Caution advised, Experimental',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Three times weekly',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'SS-31 (Elamipretide)',
    description: 'Mitochondrial-targeted tetrapeptide for cellular energy and protection',
    category: 'Metabolic',
    benefits: 'Mitochondrial protection, Cellular energy, Anti-aging, Metabolic support, Heart health',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '0.5 mg',
    dosageMax: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'Any time',
    administrationRoute: 'Intravenous',
    reconstitutionInstructions: 'Add 1 mL saline solution to 5 mg vial. Mix gently. Administer as IV infusion only.',
  },
  {
    name: 'ACE-031',
    description: 'Myostatin and ActR2B inhibitor for muscle growth and strength gains',
    category: 'Performance',
    benefits: 'Muscle growth, Strength increase, Myostatin inhibition, Lean mass gain, Athletic enhancement',
    sideEffects: 'Potential cardiovascular effects, Caution required, Experimental status, Requires monitoring',
    dosageMin: '50 mcg',
    dosageMax: '100 mcg',
    frequency: 'Every other day',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Mix by gentle swirling. Store at 2-8°C.',
  },
  {
    name: 'YK-11',
    description: 'Myostatin inhibitor SARM-like peptide for muscle building and strength',
    category: 'Performance',
    benefits: 'Muscle growth, Strength increase, Lean mass gain, Myostatin inhibition, Athletic performance',
    sideEffects: 'Potential hormonal effects, Caution advised, May affect hormones, Requires monitoring',
    dosageMin: '5 mg',
    dosageMax: '15 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Oral',
    reconstitutionInstructions: 'No reconstitution required. Take capsules with water and food.',
  },
  {
    name: 'Mechano Growth Factor (MGF)',
    description: 'IGF-1 variant supporting muscle repair and growth after training',
    category: 'Performance',
    benefits: 'Muscle repair, Growth stimulation, Recovery acceleration, Strength increase, Post-workout support',
    sideEffects: 'Mild injection site reaction, Potential systemic effects, Generally well-tolerated',
    dosageMin: '200 mcg',
    dosageMax: '400 mcg',
    frequency: 'Two to three times weekly',
    timing: 'Post-workout',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Mix gently by swirling. Store at 2-8°C.',
  },
  {
    name: 'PEG-MGF',
    description: 'Pegylated MGF with extended half-life for longer lasting effects',
    category: 'Performance',
    benefits: 'Extended muscle growth, Longer-lasting effects, Recovery enhancement, Strength increase',
    sideEffects: 'Mild injection site reaction, Potential systemic effects, Generally well-tolerated',
    dosageMin: '100 mcg',
    dosageMax: '200 mcg',
    frequency: 'Once to twice weekly',
    timing: 'Any time',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Mix by gentle swirling. Store at 2-8°C.',
  },
  {
    name: 'CJC-1295 + Ipamorelin',
    description: 'Synergistic fat loss combination of GHRH and GH secretagogue',
    category: 'Performance',
    benefits: 'Synergistic fat loss, GH stimulation, Muscle preservation, Metabolism boost, Body recomposition',
    sideEffects: 'Mild flushing, Hunger increase, Headache, Hyperglycemia, Injection site reaction',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Once to three times daily',
    timing: 'Evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'GHRP-6 + CJC-1295',
    description: 'Muscle building combination of potent GH secretagogue with GHRH analog',
    category: 'Performance',
    benefits: 'Potent GH stimulation, Muscle growth, Strength increase, Athletic enhancement, Body recomposition',
    sideEffects: 'Appetite increase, Water retention, Hyperglycemia, Potential cortisol elevation, Headache',
    dosageMin: '100 mcg',
    dosageMax: '300 mcg',
    frequency: 'Two to three times daily',
    timing: 'Before meals',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },

  // Anti-Aging & Other Specialty (10)
  {
    name: 'Oxytocin',
    description: 'Social bonding and trust hormone with relationship and mood benefits',
    category: 'Other',
    benefits: 'Social bonding, Trust enhancement, Mood improvement, Relationship support, Emotional connection',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '2 IU',
    dosageMax: '10 IU',
    frequency: 'Once to twice daily',
    timing: 'Morning or evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Available as pre-filled pens or vials. Add 0.5 mL bacteriostatic water if needed. Store at 2-8°C.',
  },
  {
    name: 'Kisspeptin-10',
    description: 'Reproductive hormone regulator for fertility and sexual function',
    category: 'Other',
    benefits: 'Reproductive hormone regulation, Fertility support, Sexual function, Hormone balance',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '50 mcg',
    dosageMax: '100 mcg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 1 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Gonadorelin',
    description: 'GnRH peptide for fertility support and reproductive hormone regulation',
    category: 'Other',
    benefits: 'Fertility support, Reproductive hormone balance, Testosterone production, Sexual function',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '25 mcg',
    dosageMax: '100 mcg',
    frequency: 'Once daily',
    timing: 'Morning or evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 2 mg vial. Mix by swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Livagen',
    description: 'Liver protection peptide supporting hepatic function and longevity',
    category: 'Anti-Aging',
    benefits: 'Liver protection, Hepatic function support, Anti-aging, Detoxification support, Longevity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Bronchogen',
    description: 'Respiratory system peptide supporting lung health and oxygen utilization',
    category: 'Anti-Aging',
    benefits: 'Respiratory support, Lung health, Oxygen utilization, Anti-aging effects, System support',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Vesugen',
    description: 'Vascular system peptide supporting cardiovascular health and circulation',
    category: 'Anti-Aging',
    benefits: 'Vascular support, Circulation improvement, Cardiovascular health, Anti-aging, Blood flow',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Cerluten',
    description: 'Brain aging peptide supporting cognitive function and neuronal health',
    category: 'Anti-Aging',
    benefits: 'Brain aging reversal, Cognitive support, Neuroprotection, Anti-aging, Neuronal health',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild headache, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix by gentle swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Cortagen',
    description: 'Cardiovascular peptide supporting heart health and anti-aging',
    category: 'Anti-Aging',
    benefits: 'Cardiovascular support, Heart health, Anti-aging effects, Metabolic support, Longevity',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '10 mg',
    dosageMax: '20 mg',
    frequency: 'Once to twice daily',
    timing: 'Morning and evening',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 10 mg vial. Mix gently. Store at 2-8°C.',
  },
  {
    name: 'Dalargin',
    description: 'Opioid peptide with immune-enhancing and anti-inflammatory properties',
    category: 'Immune',
    benefits: 'Pain relief, Anti-inflammatory, Immune modulation, Stress reduction, Gut protection',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare opioid-like effects, Generally safe',
    dosageMin: '500 mcg',
    dosageMax: '2 mg',
    frequency: 'Once to twice daily',
    timing: 'As needed',
    administrationRoute: 'Subcutaneous',
    reconstitutionInstructions: 'Add 1 mL bacteriostatic water to 5 mg vial. Mix by swirling. Refrigerate at 2-8°C.',
  },
  {
    name: 'Pentosan Polysulfate',
    description: 'Anti-inflammatory peptide compound for joint health and tissue support',
    category: 'Healing',
    benefits: 'Joint support, Anti-inflammatory, Tissue repair, Cartilage protection, Pain reduction',
    sideEffects: 'Minimal side effects, Well-tolerated, Rare mild effects, Generally safe',
    dosageMin: '100 mg',
    dosageMax: '300 mg',
    frequency: 'Once to twice daily',
    timing: 'Any time',
    administrationRoute: 'Intramuscular',
    reconstitutionInstructions: 'Available as pre-filled ampoules or vials. No reconstitution needed. Administer IM injection.',
  },
];
